MyGitTest123/MyGitTest123/Models/MessagingViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MyGitTest123.Models
{
    public class MessageViewModel
    {
        public string fromUser{ get; set; }
        public DateTime Time { get; set; }
        public string MessageText { get; set; }
        public byte[] Image { get; set; }
    }

    public class MessagesViewModel
    {
        public List<MessageViewModel> Messages;
    }

    public class SendMessageViewModel
    {
        public string MessageText { get; set; }
        public string ToUser { get; set; }
        public string FromUser { get; set; }


    }
}

MyGitTest123/MyGitTest123/Controllers/MessagingController.cs
using MyGitTest123.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using System.IO;

using System.Text;

namespace MyGitTest123.Controllers
{
    [Authorize]
    public class MessagingController : Controller
    {
    
        public ActionResult Index()
        {

            string user = User.Identity.GetUserName();
            using (var db = new MessagingContext())
            {
                var query = from m in db.Messages
                            orderby m.Time
                            where m.ToUserID == user && !m.Seen
                            select new MessageViewModel
                            {
                                fromUser = m.FromUserID,
                                MessageText = m.MessageText,
                                Time = m.Time,
                                Image = m.Image
                            };


                MessagesViewModel messagesVM = new MessagesViewModel();
                messagesVM.Messages = query.ToList();

    
                
                return View(messagesVM);

            }
        }

        public JsonResult MessagesViewed()
        {
            string user = User.Identity.GetUserName();
            using (var db = new MessagingContext())
            {

                var updateQuery = db.Messages.Where(f => f.ToUserID == user).ToList();

                updateQuery.ForEach(a => a.Seen = true);

                var ImageDeleteQuery = db.Messages.Where(f => f.ToUserID == user && f.Image != null).ToList();

                foreach(var item in ImageDeleteQuery)
                {
                    string fullPath = Request.MapPath("~/ContentUser/" + Encoding.ASCII.GetString( item.Image ));
                    if (System.IO.File.Exists(fullPath))
                    {
                        System.IO.File.Delete(fullPath);
                    }
                }

                //db.Messages.RemoveRange(db.Messages.Where(f => f.ToUserID == user && f.Image != null));
                db.SaveChanges();

                return Json(new { result = "ok" });
               

            }
        }

        [HttpPost]
        public ActionResult FileUpload(HttpPostedFileBase file)
        {
            if (file != null)
            {
                

                var fileName = Guid.NewGuid().ToString() +
                      System.IO.Path.GetExtension(file.FileName);

                string contentFolder = Server.MapPath("~/ContentUser");

                string fullFileName = Path.Combine(contentFolder, fileName);

                file.SaveAs(Path.Combine(contentFolder, fileName));

                //string pic = System.IO.Path.GetFileName(file.FileName);

                /* byte[] array = null;
                 *   using (MemoryStream ms = new MemoryStream())
                   {
                       file.InputStream.CopyTo(ms);
                       array = ms.GetBuffer();
                   }*/

                Message msg = CreateNewMessage();

                msg.Image = Encoding.ASCII.GetBytes(fileName);

                using (var db = new MessagingContext())
                {
                    db.Messages.Add(msg);
                    db.SaveChanges();
                }

                ModelState.Clear();
                return View("Index");

            }
            // after successfully uploading redirect the user
            return RedirectToAction("actionname", "controller name");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SendMessage(SendMessageViewModel model)
        {


            Message msg = CreateNewMessage();

            msg.MessageText = model.MessageText;

            using (var db = new MessagingContext())
            { 
                db.Messages.Add(msg);
                db.SaveChanges();
            }
            ModelState.Clear();
            return View("Index");
        }


        private Message CreateNewMessage()
        {
            string Name1 = "omrikon@gmail.com";
            string Name2 = "golan.idan@gmail.com";

            Message msg = new Message();
            if (User.Identity.GetUserName() == Name1)
            {
                msg.FromUserID = Name1;
                msg.ToUserID = Name2;
            }
            else
            {
                msg.FromUserID = Name2;
                msg.ToUserID = Name1;
            }

            msg.Seen = false;
            msg.Time = DateTime.Now.ToUniversalTime();

              return msg;
        }
    }
}

MyGitTest123/MyGitTest123/Views/Messaging/Index.cshtml
@using MyGitTest123.Models;
@using System.Text;
@model  MyGitTest123.Models.MessagesViewModel
@{
    ViewBag.Title = "Index";
}

<h2>What I had to say to you:</h2>

<div id="messages">
    @if (Model != null && Model.Messages != null)
    {
        foreach (var item in Model.Messages)
        {
            if (@item.Image == null)
            {
                <div>@TimeZoneInfo.ConvertTimeFromUtc(item.Time, TimeZoneInfo.FindSystemTimeZoneById("Israel Standard Time")) - 
                    @item.MessageText
               </div>
            }
            else
            {
                <div>
                   @TimeZoneInfo.ConvertTimeFromUtc(item.Time, TimeZoneInfo.FindSystemTimeZoneById("Israel Standard Time")) -
                    @Html.Raw("<a href='#img' onclick='clickHandler(event)'><img style='max-width:100px' src=\"/ContentUser/" + Encoding.ASCII.GetString(item.Image) + "\" /></a>")
            </div>
            }
        }


    }
    
</div>
<!-- lightbox container hidden with CSS -->
<a href="#_" class="lightbox" id="img">
    <img id="targetImage" src="">
</a>
<div id="input">
    @Html.Partial("_sendMessage", new SendMessageViewModel())
</div>

<script>
    window.onload = function () {
        $.ajax({
            url: "/Messaging/MessagesViewed",
            type: "POST",
            data: JSON.stringify({ 'Options': '' }),
            dataType: "json",
            traditional: true,
            contentType: "application/json; charset=utf-8",
            success: function (data) {
                if (data.result == "ok") {
                    console.log("messages deleted");
                    //$(element).closest("form").submit(); //<------------ submit form
                } else {
                    console.log("Messages not deleted");
                }
            },
            error: function () {
                console.log("Error from service");
            }
        });
    }
   
   
    function clickHandler(e)
    {
        document.getElementById('targetImage').src = e.srcElement.src;
    }
</script>

MyGitTest123/MyGitTest123/Views/Messaging/_sendMessage.cshtml
@model MyGitTest123.Models.SendMessageViewModel


<div>
    @using (Html.BeginForm("SendMessage", "Messaging", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        @Html.AntiForgeryToken()
        @Html.TextAreaFor(m => m.MessageText, new { id = "MessageText" });
        <input type="submit" value="SEND" id="btnSend" />
    }
    @using (Html.BeginForm("FileUpload", "Messaging", FormMethod.Post,
                                            new { enctype = "multipart/form-data" , id = "formUpload"}))
    {
    
        <input type="file" name="file" id="file" class="inputfile" accept=".jpg,.jpeg,.gif" style="width: 100%;" data-multiple-caption="{count} files selected"  />
        <label for="file">Choose a file</label>
        <img src="@Url.Content("~/Content/run_rabbit_3.gif")" id="gif" style="width:60px;visibility:hidden">
    }
</div>

<script>

    //$("#MessageText").autogrow();
    var inputs = document.querySelectorAll('.inputfile');
    Array.prototype.forEach.call(inputs, function (input) {
        var label = input.nextElementSibling,
            labelVal = label.innerHTML;

        input.addEventListener('change', function (e) {
            var fileName = '';
            if (this.files && this.files.length > 1)
                fileName = (this.getAttribute('data-multiple-caption') || '').replace('{count}', this.files.length);
            else
                fileName = e.target.value.split('\\').pop();

            if (fileName) {
                //label.innerHTML = fileName; 
                $("#gif").css('visibility', 'visible');
                $("#btnSend").css('visibility', 'hidden');
                document.getElementById("formUpload").submit();
            }

            else {
                label.innerHTML = labelVal;
            }


        });
    });


</script>